Stoliarenko2 Webix Jet Interaction
astoliarenko/jet-start pull request #2
Opened 2021-10-04 22:37 UTC by astoliarenko

2021-10-05 09:30 UTC, uladzislaukumakou requested changes

2021-10-05 09:30 UTC, uladzislaukumakou commented on sources/views/contacts.js
> +				": " + obj.Name + " " + obj.Email + ` ${_("from")} ` + countriesCollection.getItem(obj.Country).Name
ты используешь в одной и той же строке и обычную конкатенацию строк и es6 шаблоны? меняй все на шаблоны

2021-10-05 09:30 UTC, uladzislaukumakou commented on sources/views/contacts.js
> +		if (id && this.$$(сontactsListLocalId).exists(id)) {
2-мя строками выше присваиваешь `this.$$(сontactsListLocalId)` в переменную `list`, а здесь ее не используешь

2021-10-05 09:30 UTC, uladzislaukumakou commented on sources/views/contacts.js
> +			cols: [сontactsList, new FormView(this.app)],
вместо такой записи можно написать так и все будет работать
`cols: [сontactsList, FormView],`
если ты передаешь в конструктор JetView класса только this.app, то создавать самому объект не обязательно

2021-10-05 09:30 UTC, uladzislaukumakou commented on sources/views/data.js
> +					},
можно использовать сокращенную запись, если у тебя анонимная функция только что-то возвращает
`template: obj => _(obj.Name)`

2021-10-05 09:34 UTC, astoliarenko commented on sources/views/contacts.js
> +				": " + obj.Name + " " + obj.Email + ` ${_("from")} ` + countriesCollection.getItem(obj.Country).Name
понял

2021-10-05 09:37 UTC, astoliarenko commented on sources/views/contacts.js
> +				": " + obj.Name + " " + obj.Email + ` ${_("from")} ` + countriesCollection.getItem(obj.Country).Name
исправил

2021-10-05 13:38 UTC, uladzislaukumakou requested changes

2021-10-05 13:38 UTC, uladzislaukumakou commented on sources/views/form.js
> +				});
лучше на ивенты подписываться в методе init jetview, а не в $init компонента. потом будет очень тяжело все это искать, а так у тебя все будет в одном месте. и называй ивенты понятно, а не Combo1Select, а то это непонятно вообще что. можно назвать ивент setValueToCountriesCombo

2021-10-05 13:38 UTC, uladzislaukumakou commented on sources/views/contacts.js
>  			this.getRoot().queryView("form").setValues(item);
надо избавиться от этого queryView

2021-10-05 13:38 UTC, uladzislaukumakou commented on sources/views/contacts.js
> +			this.app.callEvent("Combo2Select", [data.Status]);
setValues вызванное от формы засетит значения и в combo, если у тебя у combo параметр name указан и в нем написано имя property из данных

2021-10-06 06:49 UTC, HelgaListopad requested changes

2021-10-06 06:49 UTC, HelgaListopad commented on sources/views/contacts.js
> +					contactsCollection.remove(id);
Если мы удаляем запись, на которой стоит селект, нужно
- очистить форму
- очистить параметр в URL

Полностью удалить параметр из URL можно через `show`, как ты делал это ниже, очистить форму - через событие

2021-10-06 06:50 UTC, HelgaListopad commented on sources/views/contacts.js
> +					contactsCollection.remove(id);
То же стоит сделать, если мы удаляем последнюю запись в таблице - иначе получается, что таблица пустая, а в форме и адресной строке у тебя остаётся старая информация. Нажмёшь Save - кинет ошибку

2021-10-06 07:41 UTC, HelgaListopad requested changes

2021-10-06 07:41 UTC, HelgaListopad commented on sources/views/contacts.js
> +					}
Не очень хорошее условие - слишком хрупкое
Я бы предложила его удалить и дополнить твой код ниже [проверкой](https://docs.webix.com/api__link__datacollection_count.html) на наличие данных в коллекции
```js
if (this.getParam("id") == id || !contactsCollection.count())
```
Причём сравнение сделать нестрогим - могут быть ситуации, когда одно и то же ID интерпретируется как строка/число

2021-10-06 07:50 UTC, astoliarenko commented on sources/views/contacts.js
> +					}
я удалил его сразу в некст коммите, тк я представил себе ситуацию что у меня должен id в url меняться , но я ведь не меняю id в коллекции после удаления элементов, поэтому смысла в нем нет

2021-10-06 07:52 UTC, astoliarenko commented on sources/views/contacts.js
> +					}
так стоп, дополнить код внизу, сейчас

2021-10-06 07:59 UTC, HelgaListopad approved these changes

2021-10-06 09:31 UTC, uladzislaukumakou approved these changes

2021-10-06 09:31 UTC, uladzislaukumakou commented on sources/views/form.js
> +				this.on(this.app, "setValueCombo1", (value) => {
еще раз повторю: подписку на ивенты надо вынести в init jetview, а не в $init самих компонентов, потому что так будет понятнее

2021-10-06 09:31 UTC, uladzislaukumakou commented on sources/views/form.js
> +				this.app.callEvent("setValueCombo2", [0]);
добавь своим combo name и тогда form.clear их очистит

2021-10-06 09:31 UTC, uladzislaukumakou commented on sources/views/contacts.js
> +			this.app.callEvent("setValueCombo2", [data.Status]);
еще раз повторяю: если ты добавишь своим combo name, который соответствует property в данных, которые ты туда хочешь засетить, то когда ты вызовешь form.setValues() у тебя все корректно засетится

2021-10-06 09:31 UTC, merged